[toolchain]
anchor_version = "0.31.0"

[features]
resolution = false
skip-lint = false
# seeds = false

[programs.localnet]
portal = "4jduFi9ShXq258vmY4GroJUYTRQnd9GWZxzK8zTxTmmw"
token_bridge = "99GM6j7R186ie7izfeHaB97LWSamFHiV8EbQVTdLuhan"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "localnet"

wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
