[toolchain]
anchor_version = "0.31.0"

[features]
resolution = false
skip-lint = false

[programs.devnet]
bridge = "6ju3gpXy6BvWECqiG41wedXsaanb5TyYzCnNzAZpDvtg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]

# Solana -> Base
wrap-token = "bun run scripts/solana-to-base/wrap-token.ts"
bridge-sol = "bun run scripts/solana-to-base/bridge-sol.ts"
bridge-spl = "bun run scripts/solana-to-base/bridge-spl.ts"
bridge-wrapped-token = "bun run scripts/solana-to-base/bridge-wrapped-token.ts"
bridge-call = "bun run scripts/solana-to-base/bridge-call.ts"

# SPL
mint-spl = "bun run scripts/spl/mint-spl.ts"
create-mint = "bun run scripts/spl/create-mint.ts"
create-user-ata = "bun run scripts/spl/create-user-ata.ts"

# Base -> Solana
prove-message = "bun run scripts/base-to-solana/prove-message.ts"

# Utils
pubkey-to-bytes32 = "bun run scripts/utils/pubkey-to-bytes32.ts"
